---
- name: Create application database
  mysql_db: name={{ percona_db_name }} state=present collation={{ percona_db_collation }}
  tags:
          - createdatabase

- name: Copy SQL dump file to the server
  copy: src={{ percona_db_dump_file }} dest=/tmp
  when: db_dump_file != ""
  tags:
          - copydumpfile
          - dumpfile

- name: Dump file into the database
  mysql_db: name={{ percona_db_name }} state=import target=/tmp/{{ percona_db_dump_file | basename }}
  when: db_dump_file != ""
  tags:
          - dumpfile

- name: Create Application user database
  mysql_user: name={{  percona_db_user }} password={{ percona_db_user_password }} priv={{ percona_db_name }}.*:ALL host={{ percona_db_host }} state=present
  tags:
          - createuserdatabase
