---
- name: Install percona database server
  action: apt pkg={{ item }} state=latest
  with_items:
          - percona-server-server-5.5
          - percona-server-client-5.5
          - percona-toolkit
          - percona-xtrabackup
          - python-mysqldb

- name: Copy .my.cnf file into the root home folder
  template: src=root-my-cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Update MySQL root password
  mysql_user: name=root host={{ item }} password={{ root_password }} login_user=root login_password={{ root_password }} check_implicit_admin=yes
  with_items:
          - "{{ ansible_hostname }}"
          - 127.0.0.1
          - localhost

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
          - "{{ ansible_hostname }}"
          - localhost

- name: remove test database
  mysql_db: name=test state=absent

- name: Delete fnv1a_64 if exists
  command: /usr/bin/mysql -e "DROP FUNCTION IF EXISTS fnv1a_64"

- name: Create fnv1a_64
  command: /usr/bin/mysql -e "CREATE FUNCTION fnv1a_64 RETURNS INTEGER SONAME 'libfnv1a_udf.so'" creates=/tmp/libfnv1a_udf.so.done

- name: Delete fnv_64 if exists
  command: /usr/bin/mysql -e "DROP FUNCTION IF EXISTS fnv_64"

- name: Create fnv_64
  command: /usr/bin/mysql -e "CREATE FUNCTION fnv_64 RETURNS INTEGER SONAME 'libfnv_udf.so'" creates=/tmp/libfnv_udf.so.done

- name: Delete murmur_hash if exists
  command: /usr/bin/mysql -e "DROP FUNCTION IF EXISTS murmur_hash"

- name: Create murmur_hash
  command: /usr/bin/mysql -e "CREATE FUNCTION murmur_hash RETURNS INTEGER SONAME 'libmurmur_udf.so'" creates=/tmp/libmurmur_udf.so.done

- name: Write custom server configuration
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root mode=0622
  notify:
          - restart percona
